export enum BidGuaranteeStatusEnum {
  DRAFT = 'DRAFT',
  REQUESTED = 'REQUESTED',
  REVIEWED = 'REVIEWED',
  REJECTED = 'REJECTED',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPRIED',
}
