export enum BidderStatusEnum {
  Registered = 200,
  Submitted = 201,
  Withdrawn = 202,
  TechnicalOpeningFailed = 301,
  TechnicalOpeningSucceeded = 302,
  TechnicalComplianceFailed = 303,
  TechnicalComplianceSucceeded = 304,
  TechnicalQualificationFailed = 305,
  TechnicalQualificationSucceeded = 306,
  TechnicalResponsivenessFailed = 307,
  TechnicalResponsivenessSucceeded = 308,
  TechnicalScoringFailed = 309,
  TechnicalScoringSucceeded = 310,
  TechnicalEvaluationFailed = 311,
  TechnicalEvaluationSucceeded = 312,

  FinancialOpeningFailed = 313,
  FinancialOpeningSucceeded = 314,

  FinancialComplianceFailed = 315,
  FinancialComplianceSucceeded = 316,
  FinancialQualificationFailed = 317,
  FinancialQualificationSucceeded = 318,
  FinancialResponsivenessFailed = 319,
  FinancialResponsivenessSucceeded = 320,
  FinancialScoringFailed = 321,
  FinancialScoringSucceeded = 322,
  FinancialEvaluationFailed = 323,
  FinancialEvaluationSucceeded = 324,
  FinancialBidPriceValuationFailed = 325,
  FinancialBidPriceValuationSucceeded = 326,

  PriceAnalysisSucceeded = 327,
  PriceAnalysisFailed = 328,
  PostQualificationSucceeded = 329,
  PostQualificationFailed = 330,

  AwardNegotiationSucceeded = 331,
  AwardNegotiationFailed = 332,

  CombinationEvaluationFailed = 333,
  CombinationEvaluationSucceeded = 334,

  AwardingFailed = 400,
  AwardingSucceeded = 401,
  Contracting = 501,
  Implementation = 601,
  Closed = 900,
  Cancelled = 999,
}
