export enum TeamRoleEnum {
  TECHNICAL_OPENER = 'TECHNICAL_OPENER',
  TECHNICAL_EVALUATOR = 'TECHNICAL_EVALUATOR',
  FINANCIAL_OPENER = 'FINANCIAL_OPENER',
  FINANCIAL_EVALUATOR = 'FINANCIAL_EVALUATOR',
}
