export enum AccountVerificationTypeEnum {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  RESET_PASSWORD = 'RESET_PASSWORD',
  PHONE_VERIFICATION = 'PHONE_VERIFICATION',
  INVITATION = 'INVITATION',
}
