export const seedRules = [
  {
    designerId: 'b3cf95c8-8e88-46e2-a146-16210150c87d',
    key: 'ruleOne',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '30000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'b3cf95c8-8e88-46e2-a146-16210150c87d',
    key: 'ruleTwo',
    executionOrder: 2,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'works',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '50000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'b3cf95c8-8e88-46e2-a146-16210150c87d',
    key: 'ruleThree',
    executionOrder: 3,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'services',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '30000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '23749813-83d3-49da-a4ee-eebc73ed3fb3',
    key: 'ruleFour',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '500000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '30000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '23749813-83d3-49da-a4ee-eebc73ed3fb3',
    key: 'ruleFive',
    executionOrder: 2,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'works',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '50000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '23749813-83d3-49da-a4ee-eebc73ed3fb3',
    key: 'ruleSix',
    executionOrder: 3,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'works',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '5000000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '23749813-83d3-49da-a4ee-eebc73ed3fb3',
    key: 'ruleSeven',
    executionOrder: 4,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'services',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '30000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'e35da0d9-2a9c-49b3-8ff9-39f8baa49ef3',
    key: 'ruleEight',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '500000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'e35da0d9-2a9c-49b3-8ff9-39f8baa49ef3',
    key: 'ruleNine',
    executionOrder: 2,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '500000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'e35da0d9-2a9c-49b3-8ff9-39f8baa49ef3',
    key: 'ruleTen',
    executionOrder: 3,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'works',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '5000000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'ea1ccc39-83de-4e94-b619-af8cc4695699',
    key: 'ruleEleven',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '20000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '6ccd1392-5ab1-4b25-be0d-732410f843c6',
    key: 'ruleTwelve',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<',
          value: '20000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'be3244d0-1bf7-4a4c-a674-fe93d74449f0',
    key: 'ruleThirteen',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '20000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'f3c9cb34-fa69-4bd4-90e4-7056b1b3fe3f',
    key: 'ruleFourteen',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '20000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '3fb1d3d5-c550-4e37-b530-a7ebc443b266',
    key: 'ruleFifteen',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<',
          value: '10000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '20ea9da6-e4f4-4ce3-9217-5ea89d8802d0',
    key: 'ruleSixteen',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '5000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '66ada819-7f8b-42a7-8c1e-3fbde6a21cd3',
    key: 'ruleSeventeen',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '50000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '5000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '66ada819-7f8b-42a7-8c1e-3fbde6a21cd3',
    key: 'rule18',
    executionOrder: 2,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '5000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '0',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'e6b12692-43c0-4477-939b-0d49f68905a5',
    key: 'rule19',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'goods',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '50000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'e6b12692-43c0-4477-939b-0d49f68905a5',
    key: 'rule20',
    executionOrder: 2,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '50000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '5000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: 'e6b12692-43c0-4477-939b-0d49f68905a5',
    key: 'rule21',
    executionOrder: 3,
    conditions: [
      [
        {
          field: 'procurementCategory',
          operator: '==',
          value: 'consultancy',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'maxValueThreshold',
          operator: '<=',
          value: '100000000',
          type: 'integer',
          joinType: '&&',
        },
        {
          field: 'minValueThreshold',
          operator: '>=',
          value: '50000000',
          type: 'integer',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '39e8d932-e626-439d-9524-425144c9b451',
    key: 'rule22',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementMethod',
          operator: '==',
          value: 'ncb',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'preferncePercentage',
          operator: '>=',
          value: '0.6',
          type: 'decimal',
          joinType: '&&',
        },
      ],
    ],
  },
  {
    designerId: '208a8196-4a10-41f6-bb4d-d11377645a7c',
    key: 'rule23',
    executionOrder: 1,
    conditions: [
      [
        {
          field: 'procurementMethod',
          operator: '==',
          value: 'rfq',
          type: 'string',
          joinType: '&&',
        },
        {
          field: 'preferentialGroup',
          operator: '<=',
          value: 'IBM',
          type: 'string',
          joinType: '||',
        },
        {
          field: 'preferentialGroup',
          operator: '<=',
          value: 'Marginalized Group',
          type: 'string',
          joinType: '||',
        },
        {
          field: 'preferentialGroup',
          operator: '<=',
          value: 'Micro',
          type: 'string',
          joinType: '||',
        },
        {
          field: 'preferentialGroup',
          operator: '<=',
          value: 'Small',
          type: 'string',
          joinType: '||',
        },
        {
          field: 'preferentialGroup',
          operator: '<=',
          value: 'Medium',
          type: 'string',
          joinType: '||',
        },
      ],
    ],
  },
];
export const seedDesigns = [
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Request for quotation',
    key: 'requestForQuotation',
    id: 'b3cf95c8-8e88-46e2-a146-16210150c87d',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'National Competitive Bidding',
    key: 'nationalCompetitiveBidding',
    id: '23749813-83d3-49da-a4ee-eebc73ed3fb3',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'International Competitive Bidding',
    key: 'internationalCompetitiveBidding',
    id: 'e35da0d9-2a9c-49b3-8ff9-39f8baa49ef3',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Short listing',
    key: 'shortListing',
    id: 'ea1ccc39-83de-4e94-b619-af8cc4695699',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Expression of Interest',
    key: 'expressionOfInterest',
    id: '6ccd1392-5ab1-4b25-be0d-732410f843c6',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'NCB Expression of Interest',
    key: 'ncbExpressionOfInterest',
    id: 'be3244d0-1bf7-4a4c-a674-fe93d74449f0',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'ICB Expression of Interest',
    key: 'icbExpressionOfInterest',
    id: 'f3c9cb34-fa69-4bd4-90e4-7056b1b3fe3f',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Single source',
    key: 'singleSource',
    id: '3fb1d3d5-c550-4e37-b530-a7ebc443b266',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Micro',
    key: 'micro',
    id: '20ea9da6-e4f4-4ce3-9217-5ea89d8802d0',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Small',
    key: 'small',
    id: '66ada819-7f8b-42a7-8c1e-3fbde6a21cd3',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [{ type: 'validate' }],
    name: 'Medium',
    key: 'medium',
    id: 'e6b12692-43c0-4477-939b-0d49f68905a5',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [
      { type: 'validate' },
      { type: 'set', name: 'recommend', value: ['comply', 'not comply'] },
    ],
    name: 'IBM Restriction Percentage',
    key: 'ibmRestrictionPercentage',
    id: '39e8d932-e626-439d-9524-425144c9b451',
  },
  {
    enforcementMethod: 'FLAG',
    actions: [
      { type: 'validate' },
      { type: 'set', name: 'recommend', value: ['comply', 'not comply'] },
    ],
    name: 'RFQ Restriction',
    key: 'rfqRestriction',
    id: '208a8196-4a10-41f6-bb4d-d11377645a7c',
  },
];
