export const FilterOperators = {
  EqualTo: '=',
  Between: 'BETWEEN',
  LessThan: '<',
  LessThanOrEqualTo: '<=',
  GreaterThan: '>',
  GreaterThanOrEqualTo: '>=',
  In: 'IN',
  NotIn: 'NotIn',
  Any: 'ANY',
  NotNull: 'NotNull',
  IsNotNull: 'IsNotNull',
  IsNull: 'IsNull',
  NotEqualTo: '!=',
  Like: 'LIKE',
  All: 'All',
  NotEqual: 'NotEqual',
};
