export enum BucketNameEnum {
  MEGP = 'megp',
  DEFAULT = '',
  SPD_TEMPLATE = 'spd/',
  SPD_CONTRACT_FORM = 'spd_contract_form/',
  SPD_BID_FORM = 'spd_bid_form/',
  TENDER_SPD_CONTRACT_FORM = 'tender_spd_contract_form/',
  TENDER_SPD_BID_FORM = 'tender_spd_bid_form/',
  TENDER_BDS = 'tender_bds/',
  TENDER_SCC = 'tender_scc/',
  SOR_DOCUMENT = 'sor_document/',
  TENDERING_DOCUMENT = 'tendering_document/',
  BID_SECURITY_DOCUMENT = 'bid_security_document/',
  BID_FORM_DOCUMENT = 'bid_form_document/',
}
