version: '3'

services:
  demo-fe:
    build:
      context: ./apps/back-office/+demo-fe
    ports:
      - "5500:5500"

  iam-fe:
    build:
      context: ./apps/back-office/iam-fe
    ports:
      - 5511:5511

  egp:
    build:
      context: ./apps/portal/egp
    ports:
      - 5599:5599
  administration:
    build:
      context: ./apps/back-office/administration-fe
    ports:
      - 5522:5522
  vendor-fe:
    build:
      context: ./apps/back-office/vendor-fe
    ports:
      - 5533:5533
