apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
      version: v1
  template:
    metadata:
      labels:
        app: portal
        version: v1
    spec:
      imagePullSecrets:
      - name: gitlab-secret
      containers:
      - name: portal
        image: gitlab.peragosystems.com:5050/megp/megp/egp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5500
        env:
            - name: NEXT_PUBLIC_AUTH_API
              value: "http://196.189.118.110:3569"
            - name: NEXT_PUBLIC_API_BASE_PATH
              value: "/api/auth"
            - name: NEXT_PUBLIC_WEBSITE_DOMAIN
              value: "http://196.189.118.110:5500"
            - name: NEXT_PUBLIC_WEBSITE_BASE_PATH
              value: "/auth"
            - name: NEXT_PUBLIC_VENDOR_API
              value: "http://196.189.118.110:5533"
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  namespace: dev
spec:
  selector:
    app: portal
    version: v1
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
  type: LoadBalancer
