export enum ERfxItemStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  INVITATION_PREPARED = 'INVITATION_PREPARED',
  SUBMITTED = 'SUBMITTED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}
