export enum ERfxStatus {
  DRAFT = 'DRAFT',
  TEAM_REVIEWAL = 'TEAM_REVIEWAL',
  ADJUSTEDMENT = 'ADJUSTEDMENT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ERfxItemStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  INVITATION_PREPARED = 'INVITATION_PREPARED',
  SUBMITTED = 'SUBMITTED',
  COMPLETED = 'COMPLETED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum EInvitationStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',

  ACCEPTED = 'ACCEPTED',
}

export enum ERfxOpenProductsStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ERfxRevisionApprovalStatusEnum {
  APPROVED = 'APPROVED',
  ADJUST = 'ADJUST',
}
