export enum ERfxStatus {
  DRAFT = 'DRAFT',
  TEAM_REVIEWAL = 'TEAM_REVIEWAL',
  ADJUSTEDMENT = 'ADJUSTEDMENT',
  SUBMITTED = 'SUBMITTED',

  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',

  ENDED = 'ENDED',
}

export enum ERfxItemStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  INVITATION_PREPARED = 'INVITATION_PREPARED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',

  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',

  ENDED = 'ENDED',
}

export enum EInvitationStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  SUBMITTED = 'SUBMITTED',

  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',

  ACCEPTED = 'ACCEPTED',
  DISCARED = 'DISCARDED',
  WITHDRAWN = 'WITHDRAWN',

  ENDED = 'ENDED',
  EXPIRED = 'EXPIRED',
}

export enum ERfxOpenProductsStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ERfxRevisionApprovalStatusEnum {
  APPROVED = 'APPROVED',
  ADJUST = 'ADJUST',
}
