export enum ERfxStatus {
  DRAFT = 'DRAFT',
  TEAM_REVIEWAL = 'TEAM_REVIEWAL',
  ADJUSTEDMENT = 'ADJUSTEDMENT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}
