apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-be
      version: v1
  template:
    metadata:
      labels:
        app: demo-be
        version: v1
    spec:
      imagePullSecrets:
      - name: gitlab-secret
      containers:
      - name: demo-be
        image: gitlab.peragosystems.com:5050/megp/megp/demo-be:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: NODE_ENV
            value: "development"
          - name: PORT
            value: "3569"
          - name: BASE_URL
            value: "http://196.189.118.110:3569"
          - name: DATABASE_HOST
            value: "196.189.44.10"
          - name: DATABASE_NAME
            value: "dev_iam"
          - name: DATABASE_USER
            value: "postgres"
          - name: DATABASE_PASSWORD
            value: "Perago@megpDB"
          - name: DATABASE_PORT
            value: "5432"
          - name: CONNECTION_URI
            value: "http://196.189.118.110:3567"
          - name: API_KEY
            value: "uibpuhokjokjbouigoih"
          - name: APP_NAME
            value: "m-egp"
          - name: API_DOMAIN
            value: "http://196.189.118.110:3569"
          - name: WEBSITE_DOMAIN
            value: "http://196.189.118.110:5500"
          - name: IAM_BACK_OFFICE_DOMAIN
            value: "http://196.189.118.110:5511"
          - name: API_BASE_PATH
            value: "/api/auth"
          - name: WEBSITE_BASE_PATH
            value: "/auth"
          - name: SMTP_HOST
            value: "smtp.elasticemail.com"
          - name: SMTP_USERNAME
            value: "mmexploit1@gmail.com"
          - name: SMTP_EMAIL
            value: "mmexploit1@gmail.com"
          - name: SMTP_PASSWORD
            value: "13CA89B5106857E132AD7933FC3E9CD4BC5B"
          - name: SMTP_PORT
            value: "2525"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-be-service
  namespace: dev
spec:
  selector:
    app: demo-be
  ports:
    - protocol: TCP
      port: 3569
      targetPort: 3569
  type: NodePort



