const bankAccounts = [
  {
    accountHoldersFullName: 'John Doe',
    accountNumber: '1234567890',
    bankName: 'Example Bank',
    bankBranchAddress: '123 Main Street, City, Country',
    currency: 'USD',
    bankSWIFT_BICCode: 'SWIFT1234',
    iBAN: 'IBAN5678',
    status: 'Active',
    hashValue: 'hash123456789',
  },
  {
    accountHoldersFullName: 'Alice Smith',
    accountNumber: '9876543210',
    bankName: 'Another Bank',
    bankBranchAddress: '456 Elm Street, Town, Country',
    currency: 'EUR',
    bankSWIFT_BICCode: 'SWIFT5678',
    iBAN: 'IBAN9876',
    status: 'Inactive',
    hashValue: 'hash987654321',
  },
  {
    accountHoldersFullName: 'Eva Johnson',
    accountNumber: '5555555555',
    bankName: 'Some Bank',
    bankBranchAddress: '789 Oak Street, Village, Country',
    currency: 'GBP',
    bankSWIFT_BICCode: 'SWIFTABCD',
    iBAN: 'IBANXYZ',
    status: 'Active',
    hashValue: 'hash555555555',
  },
  {
    accountHoldersFullName: 'Michael Brown',
    accountNumber: '1111222233',
    bankName: 'New Bank',
    bankBranchAddress: '987 Pine Street, Hamlet, Country',
    currency: 'CAD',
    bankSWIFT_BICCode: 'SWIFT9876',
    iBAN: 'IBAN1234',
    status: 'Active',
    hashValue: 'hash1111222233',
  },
];
const contactPersonsTableExamples = [
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@example.com',
    mobileNumber: '123-456-7890',
    key: 'registration-123',
  },
  {
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@email.com',
    mobileNumber: '987-654-3210',
    key: 'profile-789',
  },
  {
    firstName: 'Eva',
    lastName: 'Johnson',
    email: 'eva.j@example.com',
    mobileNumber: '555-123-4567',
    key: 'order-9876',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@example.org',
    mobileNumber: '111-222-3333',
    key: 'update-456',
  },
  {
    firstName: 'Sarah',
    lastName: 'Wilson',
    email: 'sarahwilson@email.com',
    mobileNumber: '',
    key: 'subscription-001',
  },
  {
    firstName: 'David',
    lastName: 'Johnson',
    email: 'david.j@example.org',
    mobileNumber: '555-555-5555',
    key: 'event-2023',
  },
  {
    firstName: 'Emily',
    lastName: 'Lee',
    email: 'emily.lee@example.com',
    mobileNumber: '987-987-6543',
    key: 'recovery-7890',
  },
  {
    firstName: 'Lisa',
    lastName: 'Adams',
    email: 'lisa.adams@email.com',
    mobileNumber: '123-987-4567',
    key: 'feedback-12345',
  },
  {
    firstName: 'Mark',
    lastName: 'Robinson',
    email: 'mark@example.net',
    mobileNumber: '222-333-4444',
    key: 'shipping-5678',
  },
  {
    firstName: 'Sophia',
    lastName: 'Davis',
    email: 'sophia.d@example.org',
    mobileNumber: '999-888-7777',
    key: 'support-98765',
  },
];

export const initialValues = {
  basicRegistration: {
    nameOfBusinessCompany: '',
    formOfBusiness: '',
    businessCompanyOrigin: '',
    district: '',
    country: '',
    tinNumber: '',
  },
  addressInformation: {
    postalAddress: '',
    primaryEmail: '',
    alternateEmail: '',
    mobilePhone: '',
    telephone: '',
    fax: '',
    website: '',
    geoLocation: { xCoordinate: '', yCoordinate: '' },
  },
  contactPersons: {
    contactPersonsTable: contactPersonsTableExamples,
  },
  businessSizeAndOwnership: {
    registeredCapital: { amount: '', currency: '' },
    paidUpCapital: { amount: '', currency: '' },
    numberOfEmployees: '',
    ownershipType: '',
  },
  shareHolders: {
    shareHoldersTable: [],
  },
  beneficialOwnership: {
    shareHoldersTable: [{ fullName: '', nationality: '' }],
  },
  areasOfBusinessInterest: {
    areasOfBusinessInterestNames: [],
    areasOfBusinessInterestInformation: [],
  },
  bankAccountDetails: {
    bankAccountDetailsTable: bankAccounts,
  },
  supportingDocuments: {
    businessRegistration_IncorporationCertificate: '',
    mRA_TPINCertificate: '',
    generalReceipt_BankDepositSlip: '',
    mRATaxClearanceCertificate: '',
    previousPPDARegistrationCertificate: '',
    mSMECertificate: '',
  },
};
