export enum ServiceKeyEnum {
  new = 'new',
  upgrade = 'upgrade',
  UPGRADE = 'upgrade',
  RENEWAL = 'renewal',
  update = 'update',

  PREFERENCTIAL = 'preferential',
  preferentialTreatment = 'PreferentialTreatment',
  goodsNewRegistration = 'GoodsNewRegistration',
  servicesNewRegistration = 'ServicesNewRegistration',
  worksNewRegistration = 'WorksNewRegistration',
  goodsRenewal = 'GoodsRenewal',
  servicesRenewal = 'ServicesRenewal',
  worksRenewal = 'WorksRenewal',
  goodsUpgrade = 'GoodsUpgrade',
  servicesUpgrade = 'ServicesUpgrade',
  worksUpgrade = 'WorksUpgrade',
  PROFILE_UPDATE = 'ProfileUpdate',
  IBM = 'IBM',
  MEDIUM = 'Medium',
  SMALL = 'Small',
  MICRO = 'Micro',
  MARGINALIZED_GROUP = 'Marginalized_Group',
  MSME = 'MSME',
  MG = 'MG',
  NEW_REGISTRATION = "NewRegistration",
  REGISTRATION_RENEWAL = 'RegistrationRenewal',
  REGISTRATION_UPGRADE = 'RegistrationUpgrade'
}
