export enum VendorStatusEnum {
  DRAFT = 'Draft',
  SAVE = 'Save',
  SUBMIT = 'Submit',
  SUBMITTED = 'Submitted',
  APPROVE = 'Approve',
  ADJUST = 'Adjust',
  REJECT = 'Reject',
  PPDA = 'ppda',
  COMPLETED = 'Completed',
  APPROVED = 'Approved',
  ADJUSTMENT = 'Adjustment',
  ADJUSTED = 'Adjusted',
  REJECTED = 'Rejected',
  ACTIVE = 'Active',
  PENDING = 'Pending',
  COMPLETE = 'Complete',
  DETAIL = 'Detail',
  PAYMENT = 'payment',
  RENEWAL = 'Renewal',
  DOC = 'doc',
  INFO = 'Info',
  UPDATE = 'Update',
  BASIC = 'Basic',
  PROFILE_UPDATE_KEY = 'ProfileUpdate',
  DEBARD = 'Debared'
}
