export const data = [
  {
    id: 'e95fb987-6fcf-4cb6-bbbf-16a655c4f529',
    reference: 'RFQ2024001',
    name: 'Construction of Community Center',
    envelope: 'Single Envelope',
    bid: 'Item-based',
    evaluationMethod: 'Compliance Based',
    milestone: 'Financial Opening - In Progress',
  },
  {
    id: 'ac67ac94-6b2f-4715-b0d3-eb0e2b853a6c',
    reference: 'RFP2024010',
    name: 'IT System Upgrade',
    envelope: 'Two Envelopes',
    bid: 'Lot-based',
    evaluationMethod: 'Merit Based',
    milestone: 'Technical Opening - In Progress',
  },
  {
    id: '7daab8e2-0c59-49e7-ae12-bf537c5fde6d',
    reference: 'IFB2024050',
    name: 'Road Repair and Maintenance',
    envelope: 'Single Envelope',
    bid: 'Item-based',
    evaluationMethod: 'Merit Based',
    milestone: 'Financial Opening - In Progress',
  },
  {
    id: '4cde31ab-ebb5-4b9a-afc3-1a5b48238f69',
    reference: 'RFQ2024002',
    name: 'Bridge Construction Project',
    envelope: 'Single Envelope',
    bid: 'Item-based',
    evaluationMethod: 'Merit Based',
    milestone: 'Financial Opening - In Progress',
  },
  {
    id: '9f2e7dfc-47cb-4b2d-92e7-d8df41dab9b7',
    reference: 'RFP2024011',
    name: 'New Software Development',
    envelope: 'Two Envelopes',
    bid: 'Lot-based',
    evaluationMethod: 'Compliance Based',
    milestone: 'Technical Opening - In Progress',
  },
  {
    id: '3e4b0cf0-2ba4-4b0f-97f7-41ff62d9bc7e',
    reference: 'IFB2024051',
    name: 'School Renovation Project',
    envelope: 'Single Envelope',
    bid: 'Item-based',
    evaluationMethod: 'Compliance Based',
    milestone: 'Technical Opening - In Progress',
  },
  {
    id: '8ab476e1-cb2d-4c76-82a9-b15581b40c29',
    reference: 'RFQ2024003',
    name: 'Water Treatment Plant Upgrade',
    envelope: 'Single Envelope',
    bid: 'Item-based',
    evaluationMethod: 'Merit Based',
    milestone: 'Financial Opening - In Progress',
  },
];
