export const FilterOperators = {
  EqualTo: '=',
  Between: 'BETWEEN',
  LessThan: '<',
  LessThanOrEqualTo: '<=',
  GreaterThan: '>',
  GreaterThanOrEqualTo: '>=',
  In: 'IN',
  NotIn: 'notIn',
  Any: 'ANY',
  NotNull: 'notNull',
  IsNotNull: 'isNotNull',
  IsNull: 'isNull',
  NotEqualTo: '!=',
  Like: 'LIKE',
  All: 'all',
  NotEqual: 'notEqual',
};
