export enum ApplicationStatus {
  DRAFT = 'Draft',
  SUBMIT = 'Submit',
  ADJUST = 'Adjust',
  SUBMITTED = 'Submitted',
  COMPLETED = 'Completed',
  INPROGRESS = 'Inprogress',
  APPROVED = 'Approved',
  REJECTED = 'Rejected',
  OUTDATED = 'Outdated',
  PENDING = 'Pending',
  ADJUSTMENT = 'Adjustment',
  CANCEL = 'Cancel',
  CANCELED = 'Canceled',
  APPROVE = 'Approve',
  REJECT = 'Reject',
}
