import { NCICResponseDTO } from './dto/api-ncic.dto';

export const NcicMockData: NCICResponseDTO[] = [
  {
    tenantId: 0,
    id: 'ec50830d-e018-42f2-b42e-a94d8c43626d',
    tin: '20202020',
    nameOfFirm: 'ABC Enterprises',
    postalAddress: '123 Main Street, Cityville',
    telephoneNumber: '123-456-7890',
    email: 'abc@example.com',
    nationalOfFirm: 'Country A',
    typeOfRegistration: 'Private Limited',
    branch: 'Main Branch',
    category: 'Retail',
    district: 'City District',
    region: 'Central Region',
  },
  {
    tenantId: 1,
    id: 'f1a2b3c4-d5e6-789f-a0b1-c2d3e4f5g6h7',
    tin: '30303030',
    nameOfFirm: 'XYZ Corporation',
    postalAddress: '456 Elm Street, Townville',
    telephoneNumber: '987-654-3210',
    email: 'xyz@example.com',
    nationalOfFirm: 'Country B',
    typeOfRegistration: 'Public Limited',
    branch: 'Downtown Branch',
    category: 'Wholesale',
    district: 'Town District',
    region: 'Western Region',
  },
  {
    tenantId: 2,
    id: 'g8h9i0j1-k2l3-m4n5-o6p7-q8r9s0t1u2v3',
    tin: '40404040',
    nameOfFirm: '123 Solutions Ltd.',
    postalAddress: '789 Oak Avenue, Villageton',
    telephoneNumber: '456-789-0123',
    email: 'info@123solutions.com',
    nationalOfFirm: 'Country C',
    typeOfRegistration: 'Limited Liability',
    branch: 'North Branch',
    category: 'Services',
    district: 'Village District',
    region: 'Northern Region',
  },
  {
    tenantId: 3,
    id: 'w5x6y7z8-9a0b-c1d2-e3f4-g5h6i7j8k9l0',
    tin: '50505050',
    nameOfFirm: 'PQR Innovations Inc.',
    postalAddress: '321 Pine Road, Suburbia',
    telephoneNumber: '234-567-8901',
    email: 'contact@pqrinnovations.com',
    nationalOfFirm: 'Country D',
    typeOfRegistration: 'Partnership',
    branch: 'East Branch',
    category: 'Technology',
    district: 'Suburb District',
    region: 'Eastern Region',
  },
  {
    tenantId: 4,
    id: 'm2n3o4p5-q6r7-s8t9-u0v1-w2x3y4z5a6',
    tin: '60606060',
    nameOfFirm: 'LMN Enterprises',
    postalAddress: '987 Maple Lane, Hamletville',
    telephoneNumber: '345-678-9012',
    email: 'info@lmnenterprises.com',
    nationalOfFirm: 'Country E',
    typeOfRegistration: 'Sole Proprietorship',
    branch: 'West Branch',
    category: 'Manufacturing',
    district: 'Hamlet District',
    region: 'Southern Region',
  },
  {
    tenantId: 5,
    id: 'b7c8d9e0-f1g2-h3i4-j5k6-l7m8n9o0p1',
    tin: '70707070',
    nameOfFirm: 'RST Holdings',
    postalAddress: '654 Cedar Street, Ruralton',
    telephoneNumber: '567-890-1234',
    email: 'contact@rstholdings.com',
    nationalOfFirm: 'Country F',
    typeOfRegistration: 'Limited Partnership',
    branch: 'South Branch',
    category: 'Finance',
    district: 'Rural District',
    region: 'Western Region',
  },
  {
    tenantId: 6,
    id: 'q2w3e4r5-t6y7-u8i9-o0p1-a2s3d4f5g6h',
    tin: '80808080',
    nameOfFirm: 'UVW Solutions',
    postalAddress: '789 Birch Boulevard, Outskirtsville',
    telephoneNumber: '678-901-2345',
    email: 'info@uvwsolutions.com',
    nationalOfFirm: 'Country G',
    typeOfRegistration: 'Joint Venture',
    branch: 'Central Branch',
    category: 'Consulting',
    district: 'Outskirt District',
    region: 'Central Region',
  },
  {
    tenantId: 7,
    id: 'i3o4p5q6-r7s8t9u0-v1w2x3y4z5a6b',
    tin: '90909090',
    nameOfFirm: 'EFG Retailers',
    postalAddress: '234 Walnut Street, Metropolis',
    telephoneNumber: '789-012-3456',
    email: 'info@efgretailers.com',
    nationalOfFirm: 'Country H',
    typeOfRegistration: 'Franchise',
    branch: 'Main Branch',
    category: 'Retail',
    district: 'Metropolis District',
    region: 'Eastern Region',
  },
];
