stages:
  - build
  #- test
  #- push
  - deploy
variables:
  DEMOFE_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DEMOFE_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


build_demo_fe:
  stage: build
  only:
    changes:
      - "*"  # run pipeline if a root-level file like Makefile or docker-compose.yml is changed
      - "apps/back-office/+demo-fe/**/*" 

  image: docker:latest
  services:
    - docker:dind
  script:
    - cd apps/back-office/+demo-fe
    - docker build -t $DEMOFE_TEST_IMAGE .
    - docker tag  $DEMOFE_TEST_IMAGE $DEMOFE_RELEASE_IMAGE
    - docker push $DEMOFE_TEST_IMAGE


deploy_demo_fe:
  stage: deploy
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always

  script:
    - docker pull $DEMOFE_RELEASE_IMAGE
    - docker container rm -f demo || true
    - docker run -d -p 5599:5599 --name demo $DEMOFE_RELEASE_IMAGE
  

