stages:
  - build
  - test
  - push
  - deploy

build_demo_fe:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd apps/back-office/+demo-fe
    - docker build -t demo-fe:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    - docker push demo-fe:$CI_COMMIT_REF_SLUG


push_demo_fe:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull demo-fe:$CI_COMMIT_REF_SLUG
    - docker tag demo-fe:$CI_COMMIT_REF_SLUG demo-fe:latest
    - docker push demo-fe:latest

deploy_demo_fe:
  stage: deploy
  script:
    - docker pull demo-fe:latest
    - docker
